#!/usr/bin/env bash
# Install Terrafrom and Kops in Ubuntu 18.04
# Install Jq

sudo apt-get --yes update \
&& sudo apt-get --yes install jq \
&& sudo apt-get --yes install unzip || log "ERROR: Failed update" $?
TERRAFORM_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
TERRAFORM_URL="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" 

AWS_CLI_URL="https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"

log()
{
         exit_code=$2
		 if [ -z $2 ]; then
		    exit_code=0
		 fi

		 echo "[`date '+%Y-%m-%d %T'`]:" $1
		 if [ ${exit_code} -ne "0" ]; then
		   exit ${exit_code}
		 fi
}

# Download and setup required softwares for Job Portal application
Git_setup(){
    log "INFO: Start Git Installation"
        echo "======================================================================================"
    apt install git-all -y
}

python_setup(){
    log "INFO: Start Python Installation"
    apt-get install python3-pip apache2 libapache2-mod-wsgi-py3 -y || log  "ERROR: Python Installation failed" $?
    log "INFO: Python Installation Complete"
}

python_virtualenv_setup(){
    log "INFO: Start Python Virtual environment setup"
    pip3 install virtualenv -y || log  "ERROR: Python virtual environment setup failed" $?
    log "INFO: Python virtual environment setup Complete"
}

Create_directory(){
    log "INFO: Create a directory called django"
    mkdir /home/django || log  "ERROR: django directory creation error" $?
    log "INFO: django directory creation Complete"
}

#Download and Setup Terraform
terraform_setup(){
    log "INFO: Download Terraform -> Version ${TERRAFORM_VERSION}"
    curl -sLO ${TERRAFORM_URL} || log  "ERROR: Downlaod failed" $?
    log "INFO: Download Complete"
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip || log "ERROR: Unzipping terraform_${TERRAFORM_VERSION}_linux_amd64.zip" $?
    chmod +x terraform || log "ERROR: Cant set the executable permission" $?
    if [ -d '/usr/local/bin' ]; then
        sudo mv terraform /usr/local/bin/terraform || log "ERROR: Moving Terraform Failed"  $?
    else
        log "ERROR: /usr/local/bin Directory Not found"
    fi
}

#Download and Setup AWS_CLI
aws_cli_setup(){
    log "INFO: Download aws cli -> Version 2.0.6"
    curl -sLO ${AWS_CLI_URL} || log  "ERROR: Downlaod failed" $?
    log "INFO: Download Complete"
    sudo mv awscli-exe-linux-x86_64.zip awscliv2.zip || log "ERROR: renaming file to readable name Failed" $?
    unzip awscliv2.zip || log "ERROR: Unzipping awscliv2.zip" $?
    ./aws/install || log "ERROR: Cant execute aws cli" $?
}
verify_install(){
 
    log "INFO: VERIFY GITS"
    git --version || log "ERROR: GIT verification failed" $?

    log "INFO: VERIFY PYTHON"
    pip3 --version || log "ERROR: kubectl verification failed" $?

    log "INFO: VERIFY libapache2-mod-wsgi-py3"
    dpkg -l | grep wsgi || log "ERROR: libapache2-mod-wsgi-py3 verification failed" $?

    log "INFO: VERIFY APACHE"
    httpd -v || log "ERROR: Apache verification failed" $?

    log "INFO: VERIFY TERRAFORM"
    terraform --version || log "ERROR: terraform verification failed" $?

    log "INFO: VERIFY AWS CLI"
    aws --version || log "ERROR: aws cli verification failed" $?

    log "INFO: Validation Successful !!!"
    rm -f terraform_0.11.13_linux_amd64.zip || log "ERROR: terraform zip Cleanup failed" $?

}

echo "======================================================================================"
Git_setup
sleep 2
echo "======================================================================================"
python_setup
sleep 2
echo "======================================================================================"
terraform_setup
sleep 2
echo "======================================================================================"
aws_cli_setup
sleep 2
echo "======================================================================================"
verify_install
echo "======================================================================================"
